version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
  #  steps:
   #   - checkout
   #   - run:
    #      name: Greeting
    #      command: echo Hello, world.
  #    - run:
  #        name: Print the Current Time
   #       command: date

## Set the artifacts
general:
  artifacts:
    - "./tests/screenshots" #Save the screenshots for the tests
 
 
## Customize dependencies

dependencies:
  pre:

  # Install Selenium.
  - curl http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar > selenium-server-standalone.jar
  - curl http://chromedriver.storage.googleapis.com/2.23/chromedriver_linux64.zip | gzip -dc > chromedriver
  - chmod +x chromedriver
  - 'java -jar selenium-server-standalone.jar -trustAllSSLCertificates -Dwebdriver.chrome.driver=chromedriver':
        background: true
  # Update Google Chrome.
  - google-chrome --version
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb stable main" >> /etc/apt/sources.list.d/google.list'
  - sudo apt-get update
  - sudo apt-get --only-upgrade install google-chrome-stable
  - google-chrome --version
  
  ## Running Tests
test:
   override:
    - CircleCISelenium/CoreTest/src/FunctionalTest/CoreTestScript.java 
