version: 2
jobs:
  build:
    
   working_directory: ~/krishnmohan/CircleCISelenium

    docker:
  - image: circleci/openjdk:8-jdk
  

  environment:
      # Customize the JVM maximum heap limit
         MAVEN_OPTS: -Xmx3200m
      
  
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: mvn dependency:go-offline 
   # - run: cd CoreTest && mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
        
      # run tests!
- run: mvn integration-test
