version: 2
jobs:
  build:
    docker:
     # - image: circleci/openjdk:8-jdk-browsers
      
    - image: circleci/openjdk
      
 
          
          
          general:
  artifacts:
    - "./screenshots" #Save the screenshots for all the tests
- "./log" #Save the logs for all the tests

## Customize dependencies
dependencies:
  pre:
    - sudo pip install -U selenium
    - sudo apt-get update
    - sudo apt-get install nginx
     # Copy the html page to nginx default public www location
    - sudo cp ./selenium-tutorial-main.html /var/www/html/selenium-tutorial-main.html
 
## Running Tests
test:
  # The key call to clone the test repository before we run the test
  pre:
    - git clone https://github.com/krishnmohan/CircleCISelenium.git

  # Running Tests
 test:
   override:
    - CircleCISelenium/CoreTest/src/FunctionalTest/CoreTestScript.java 
