version: 2
jobs:
  build:
    
    working_directory: ~/krishnmohan/CircleCISelenium

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout

      - restore_cache:
          key: krishnmohan/CircleCISelenium-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: krishnmohan/CircleCISelenium-{{ checksum "pom.xml" }}
      
      - run: mvn package
      
      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: target/demo-java-spring-0.0.1-SNAPSHOT.ja
          
## Running Tests
##test:
##   override:
  ##  - java  CircleCISelenium/CoreTest/src/FunctionalTest/CoreTestScript.java
