version: 2
jobs:
  build:
    docker:
           - image: circleci/openjdk:8-jdk-browsers
   steps:
      - checkout
      - run: mkdir test-reports
      - run:
          name: Download Selenium
          command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Start Selenium
          command: java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
          background: true
          
          
          general:
  artifacts:
    - "./screenshots" #Save the screenshots for all the tests
- "./log" #Save the logs for all the tests

## Customize dependencies
dependencies:
  pre:
    - sudo pip install -U selenium
    - sudo apt-get update
    - sudo apt-get install nginx
     # Copy the html page to nginx default public www location
    - sudo cp ./selenium-tutorial-main.html /var/www/html/selenium-tutorial-main.html
 
## Running Tests
test:
  # The key call to clone the test repository before we run the test
  pre:
    - git clone https://github.com/krishnmohan/CircleCISelenium.git

  # Running Tests
 test:
   override:
    - CircleCISelenium/CoreTest/src/FunctionalTest/CoreTestScript.java 
